Repository FuelLabs/fuelup, pull requests merged in 2022-09, with the labels that each got.

#166 update tests for `forc-client` inclusion
  tests/commands.rs
  tests/testcfg.rs
Labels: enhancement

#172 nightly ci include semver
  .github/workflows/scripts/index-versions.sh
Labels: ci

#174 show dates for `fuelup show` in nightly
  src/ops/fuelup_show.rs
Labels: enhancement

#168 Add nightly channel page to fuelup book
  docs/src/SUMMARY.md
  docs/src/concepts/channels/index.md
  docs/src/concepts/channels/nightly.md
Labels: documentation, book

#175 bump v0.5.0
  Cargo.lock
  Cargo.toml
Labels: release

#176 docs: update quickstart
  docs/src/installation/index.md
Labels: book

#180 chore: rename index-version.sh -> append_package_to_channel.sh
  .github/workflows/publish-nightly-channel.yml
  .github/workflows/scripts/append_package_to_channel.sh
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci

#183 install std and core libs on installing `forc`
  src/toolchain.rs
Labels: enhancement

#187 feat: auto detect http proxy setting.
  src/download.rs
Labels: enhancement

#193 fix: date format when publishing
  .github/workflows/scripts/append_package_to_channel.sh
Labels: ci

#194 bump v0.6.0
  Cargo.lock
  Cargo.toml
Labels: release

#201 ci: publish forc-client in CI
  .github/workflows/publish-nightly-channel.yml
  .github/workflows/scripts/append_package_to_channel.sh
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci

#206 release: v0.7.0
  Cargo.lock
  Cargo.toml
Labels: release

#209 fix forc-client tests
  tests/commands.rs
  tests/testcfg.rs
Labels: bug

#211 fix: update component remove
  component/src/lib.rs
  components.toml
  src/ops/fuelup_component/add.rs
  src/toolchain.rs
Labels: bug

#212 release: bump 0.7.1
  Cargo.lock
  Cargo.toml
Labels: release

#214 refactor: deprecate append_package_to_channel
  .github/workflows/scripts/append_package_to_channel.sh
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci, code quality

#217 custom toolchain: creating a new toolchain should set it as default
  src/ops/fuelup_toolchain/new.rs
  tests/commands.rs
  tests/testcfg.rs
Labels: enhancement

#215 refactor: deprecate usage of consts
  component/src/lib.rs
  src/constants.rs
  src/download.rs
  src/target_triple.rs
  src/toolchain.rs
Labels: code quality
