Repository FuelLabs/fuelup, pull requests merged in 2022-05, with the labels that each got.

#8 minimum viable fuelup
  Cargo.toml
  fuelup-init.sh
  fuelup/fuelup
  src/commands/install.rs
  src/commands/mod.rs
  src/constants.rs
  src/download.rs
  src/lib.rs
  src/main.rs
Labels: enhancement

#25 Add CI to publish `fuelup-init.sh`
  .github/workflows/gh-pages-init.yml
  README.md
Labels: ci

#28 Fix fuelup-init.sh and make it sh-compliant.
  fuelup-init.sh
Labels: bug

#35 Add lint and publish check CI jobs.
  .github/scripts/verify_tag.sh
  .github/workflows/ci.yml
  Cargo.toml
Labels: ci

#42 update cut command
  fuelup-init.sh
Labels: bug

#55 Try sh ci actions
  .github/workflows/ci.yml
  fuelup-init.sh
Labels: ci
