Repository FuelLabs/fuelup, pull requests merged in 2022-06, with the labels that each got.

#56 bootstrap ci tests
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/download.rs
Labels: ci, testing

#61 fuelup option to add to path
  fuelup-init.sh
Labels: enhancement

#57 Gracefully handle errors for `download_file`
  src/commands/install.rs
  src/download.rs
Labels: enhancement

#70 remove need_tty
  fuelup-init.sh
Labels: enhancement

#74 update README with updated instructions
  README.md
Labels: documentation

#73 support `latest` toolchain and run commands in proxy
  Cargo.lock
  Cargo.toml
  fuelup-init.sh
  src/commands/fuelup.rs
  src/commands/install.rs
  src/commands/mod.rs
  src/commands/toolchain.rs
  src/component.rs
  src/constants.rs
  src/download.rs
  src/file.rs
  src/fuelup_cli.rs
  src/lib.rs
  src/main.rs
  src/ops/fuelup_self.rs
  src/ops/fuelup_toolchain.rs
  src/ops/mod.rs
  src/path.rs
  src/proxy_cli.rs
  src/settings.rs
  src/toolchain.rs
Labels: enhancement

#64 `fuelup check`
  Cargo.lock
  Cargo.toml
  src/commands/check.rs
  src/commands/mod.rs
  src/config.rs
  src/fmt.rs
  src/fuelup_cli.rs
  src/lib.rs
  src/main.rs
  src/ops/fuelup_check.rs
  src/ops/fuelup_toolchain.rs
  src/ops/mod.rs
  src/path.rs
  src/toolchain.rs
Labels: enhancement

#82 Update post-installation instructions
  fuelup-init.sh
Labels: documentation, fuelup-init

#75 index versions
  .github/workflows/index-versions.yml
  .github/workflows/scripts/index-versions.sh
Labels: enhancement

#85 fix script location
  .github/workflows/index-versions.yml
Labels: bug

#84 correctly pass args to fuelup
  .github/workflows/ci.yml
  fuelup-init.sh
Labels: bug, fuelup-init

#89 update README
  README.md
Labels: documentation

#90 add missing 'v' to release link
  fuelup-init.sh
Labels: fuelup-init

#92 fix bug with `index-versions.sh` that causes hashes to sometimes be empty
  .github/workflows/index-versions.yml
  .github/workflows/scripts/index-versions.sh
Labels: bug

#94 include .github/workflows/scripts dir in shfmt and shellcheck CI checks
  .github/workflows/ci.yml
  .github/workflows/scripts/verify_tag.sh
Labels: ci
