Repository FuelLabs/fuelup, pull requests merged in 2023-03, with the labels that each got.

#407 fix: script lint checks
  .github/workflows/scripts/append_package_to_channel.sh
  fuelup-init.sh
Labels: ci, fuelup-init

#409 Update installation URLs
  README.md
  docs/src/installation/index.md
  src/ops/fuelup_self.rs
Labels: bug, documentation

#413 feat: agent abstraction
  src/download.rs
  src/ops/fuelup_toolchain/list_revisions.rs
Labels: enhancement

#414 ci: index other components
  .github/workflows/index-versions.yml
  Cargo.lock
  ci/compare-versions/Cargo.toml
  ci/compare-versions/src/main.rs
  tests/expects/mod.rs
Labels: ci, new feature

#416 fix: do not run if no channel published
  .github/workflows/index-versions.yml
Labels: bug, ci
