Repository FuelLabs/fuelup, pull requests merged in 2023-08, with the labels that each got.

#458 feat: docs-hub CI test
  .github/workflows/docs.yml
  .github/workflows/markdown-lint.yml
  docs/.gitignore
  docs/src/concepts/how_fuelup_works.md
  docs/src/developer_guide/building_a_channel.md
  docs/src/overrides.md
Labels: documentation

#464 docs: small fixes
  docs/src/concepts/channels.md
  docs/src/configuration.md
Labels: book

#467 feat: add `beta-4-rc-2` dist channel support
  docs/src/concepts/channels.md
  src/channel.rs
  src/constants.rs
  src/toolchain.rs
Labels: enhancement

#470 chore: bump to v0.19.3
  Cargo.lock
  Cargo.toml
Labels: release

#472 feat: support `fuel-core-keygen` binary
  ci/build-channel/src/main.rs
  component/src/lib.rs
  components.toml
  tests/show.rs
Labels: enhancement, P: Critical

#475 ci: use rust 1.71 in ci
  .github/workflows/test-toolchain-compatibility.yml
Labels: bug, ci

#476 fix: remove incorrect incompatabile versions flagged by fuelup
  incompatible-versions/forc-0.44.1@fuel-core-0.18.3
  incompatible-versions/forc-0.44.1@fuel-core-0.19.2
  incompatible-versions/forc-0.44.1@fuel-core-0.20.3
  incompatible-versions/forc-0.44.1@fuel-core-0.20.4
Labels: bug

#477 fix: remove incorrect incompatabile versions flagged by fuelup
  incompatible-versions/forc-0.44.1@fuel-core-0.18.3
  incompatible-versions/forc-0.44.1@fuel-core-0.19.2
  incompatible-versions/forc-0.44.1@fuel-core-0.20.3
  incompatible-versions/forc-0.44.1@fuel-core-0.20.4
Labels: bug

#473 chore: bump to v0.19.4
  Cargo.lock
  Cargo.toml
Labels: release

#474 fix: canonicalize path for tmp test directories
  tests/testcfg/mod.rs
Labels: bug
