Repository FuelLabs/fuelup, pull requests merged in 2023-09, with the labels that each got.

#482 release: add beta-4 toolchain manifest
  channel-fuel-beta-4.toml
Labels: release

#480 feat: add beta-4 support
  docs/src/concepts/channels.md
  src/channel.rs
  src/constants.rs
  src/toolchain.rs
Labels: enhancement

#483 chore: bump to v0.19.5
  Cargo.lock
  Cargo.toml
Labels: release

#486 Update toolchain help message
  src/commands/toolchain.rs
  src/toolchain_override.rs
Labels: enhancement

#488 ci: use bigger image to run check-versions ci workflow
  .github/workflows/index-versions.yml
Labels: ci
