Repository FuelLabs/fuelup, pull requests merged in 2023-01, with the labels that each got.

#326 update nightly channel building; handle ureq error
  Cargo.lock
  ci/build-channel/Cargo.toml
  ci/build-channel/src/main.rs
Labels: ci

#332 feat: `fuelup show` should show the overridden toolchain
  src/ops/fuelup_show.rs
  tests/commands.rs
Labels: new feature

#317 feat: allow usage of fuel-toolchain.toml in projects
  docs/src/SUMMARY.md
  docs/src/overrides.md
  src/constants.rs
  src/lib.rs
  src/ops/fuelup_default.rs
  src/ops/fuelup_show.rs
  src/path.rs
  src/proxy_cli.rs
  src/store.rs
  src/toolchain.rs
  src/toolchain_override.rs
  tests/commands.rs
  tests/testcfg.rs
Labels: new feature

#328 ci: publish latest twice to include one with date
  .github/workflows/publish-nightly-channel.yml
  .github/workflows/test-toolchain-compatibility.yml
  ci/build-channel/src/main.rs
Labels: ci

#340 fix: default bug
  src/ops/fuelup_default.rs
  src/toolchain.rs
  tests/commands.rs
Labels: bug

#341 fix: nightly workflow
  .github/workflows/publish-nightly-channel.yml
Labels: bug, ci

#344 Fix crash when `.fuelup` doesn't exist
  src/settings.rs
Labels: bug

#345 release: v0.16.0
  Cargo.lock
  Cargo.toml
Labels: release

#346 fix: include beta toolchains in override error messages
  src/toolchain_override.rs
Labels: bug

#347 release: bump v0.16.1
  Cargo.lock
  Cargo.toml
Labels: release

#337 refactor: update nightly publishes
  ci/build-channel/src/main.rs
Labels: ci

#350 fix: nightly publishing overwriting
  ci/build-channel/src/main.rs
Labels: bug, ci

#349 refactor: break up command.rs into files per subcommand
  tests/check.rs
  tests/commands.rs
  tests/completions.rs
  tests/component.rs
  tests/default.rs
  tests/expects/mod.rs
  tests/self.rs
  tests/show.rs
  tests/testcfg/mod.rs
  tests/toolchain.rs
  tests/update.rs
  tests/version.rs
Labels: good first issue, testing, code quality

#357 relink fuelup to components to push updates
  src/ops/fuelup_self.rs
Labels: bug

#354 fix: install overridden components to store instead of to the toolchain dir
  component/src/lib.rs
  src/proxy_cli.rs
  src/store.rs
  src/toolchain.rs
Labels: bug, P: Critical

#358 fix: fuelup show display string
  src/ops/fuelup_show.rs
Labels: bug

#359 release: v0.16.2
  Cargo.lock
  Cargo.toml
Labels: release

#360 fix(ci): missing install step in CI
  .github/workflows/ci.yml
Labels: bug, ci

#368 docs: add section on adding components to fuelup
  docs/src/SUMMARY.md
  docs/src/developer_guide/adding_components.md
  docs/src/developer_guide/contributing_to_fuelup.md
  docs/src/developer_guide/index.md
Labels: documentation

#365 fix: `fuelup check --verbose` showing wrong output
  component/src/lib.rs
  src/ops/fuelup_check.rs
Labels: bug
