Repository FuelLabs/fuelup, pull requests merged in 2023-02, with the labels that each got.

#375 feat: add ability to list latest revisions
  src/commands/toolchain.rs
  src/ops/fuelup_toolchain/list_revisions.rs
  src/ops/fuelup_toolchain/mod.rs
Labels: new feature

#378 ci: update toolchain compatibility tests
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci

#379 bug(ci): add missing with
  .github/workflows/test-toolchain-compatibility.yml
Labels: bug, ci

#376 release: 0.17.0
  Cargo.lock
  Cargo.toml
Labels: release

#380 ci: small update to frequency of checks
  .github/workflows/index-versions.yml
Labels: ci

#386 release: v0.17.1
  Cargo.lock
  Cargo.toml
Labels: release

#383 release: v0.18.0
  Cargo.lock
  Cargo.toml
Labels: release

#388 ci: build sway-libs
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci

#389 ci: cd into s way when testing
  .github/workflows/test-toolchain-compatibility.yml
Labels: ci

#384 ci: check for failure for new tests
  .github/workflows/test-toolchain-compatibility.yml
Labels: bug, ci

#393 docs: update README with developer guide links
  README.md
Labels: documentation

#394 fix: add fuel-core-keygen to expected files
  tests/component.rs
Labels: bug

#392 ci: refactor `build-channel` and add documentation
  .github/workflows/publish-nightly-channel.yml
  .github/workflows/test-toolchain-compatibility.yml
  ci/build-channel/src/main.rs
  docs/src/SUMMARY.md
  docs/src/developer_guide/building_a_channel.md
  docs/src/developer_guide/index.md
Labels: documentation, ci

#398 docs: improve `build-channel` docs
  docs/src/developer_guide/building_a_channel.md
  docs/src/developer_guide/index.md
Labels: documentation

#396 fix: link fuelup and not the binary
  src/toolchain.rs
Labels: bug

#397 release: v0.18.1
  Cargo.lock
  Cargo.toml
Labels: release

#400 Add beta-3 entry under Channels in Fuelup book
  docs/src/concepts/channels/beta-3.md
  docs/src/concepts/channels/index.md
Labels: documentation, enhancement, P: Critical, book

#401 test: general cleanup
  tests/default.rs
  tests/show.rs
  tests/testcfg/mod.rs
  tests/toolchain.rs
Labels: testing

#404 test: add a way to test switching toolchains/overrides
  tests/show.rs
  tests/testcfg/mod.rs
Labels: testing
