Repository FuelLabs/fuelup, pull requests merged in 2023-07, with the labels that each got.

#450 fix: add missing forc-wallet entries for 2023-07-05 latest run
  channel-fuel-latest.toml
  channels/latest/channel-fuel-latest-2023-07-05.toml
Labels: bug

#454 chore: add fuel-beta-4-rc channel toml file
  fuel-beta-4-rc.toml
Labels: release

#456 fix: prefix fuel-beta-4 channel name with `channel-`
  channel-fuel-beta-4-rc.toml
Labels: bug

#451 doc: add section for `beta-4-rc` channel
  docs/src/concepts/channels.md
Labels: documentation
