Repository FuelLabs/fuelup, pull requests merged in 2024-07, with the labels that each got.

#644 remove forc explore
  components.toml
  docs/src/concepts/components.md
  fuelup-init.sh
  tests/show.rs
  tests/testcfg/mod.rs
  tests/update.rs
Labels: breaking

#646 Bump fuel-core to v0.30.0 for testnet
  channel-fuel-testnet.toml
Labels: release

#645 Docs improvements
  docs/src/concepts/channels.md
  docs/src/developer_guide/contributing_to_fuelup.md
Labels: documentation

#647 bump testnet to use fuel-core v0.31.0
  channel-fuel-testnet.toml
Labels: release

#648 chore: bump to v0.26.0
  Cargo.lock
  Cargo.toml
Labels: release
