Repository FuelLabs/fuelup, pull requests merged in 2024-06, with the labels that each got.

#625 feat: add upgrade command to auto update fuelup, switch to latest and update installed channels
  src/commands/mod.rs
  src/commands/upgrade.rs
  src/fuelup_cli.rs
  src/ops/fuelup_upgrade.rs
  src/ops/mod.rs
  tests/upgrade.rs
Labels: enhancement

#626 chore: bump to v0.25.1
  Cargo.lock
  Cargo.toml
Labels: release

#628 Add `beta-5` and `testnet` to the channels section of the book.
  docs/src/concepts/channels.md
  src/commands/toolchain.rs
  src/toolchain_override.rs
Labels: book

#639 Add the indoc crate to help clean up examples
  Cargo.lock
  Cargo.toml
  component/Cargo.toml
  component/src/lib.rs
  src/download.rs
  src/toolchain_override.rs
  tests/component.rs
  tests/show.rs
Labels: code quality

#641 ci: enable test coverage tracking
  .github/workflows/ci.yml
Labels: ci, code quality
