Repository FuelLabs/fuelup, pull requests merged in 2024-10, with the labels that each got.

#669 Update component target tarball (#654)
  components.toml
  tests/testcfg/mod.rs
Labels: bug, fuelup

#679 chore: bump version to v0.27.0
  Cargo.lock
  Cargo.toml
Labels: release

#683 Add tests and highlight issues with should_panic
  Cargo.lock
  Cargo.toml
  component/src/lib.rs
  src/target_triple.rs
  src/toolchain_override.rs
  tests/testcfg/mod.rs
  tests/toolchain.rs
Labels: bug, testing, code quality, fuelup, overrides

#665 Fix incorrect binary link target
  src/toolchain.rs
  tests/toolchain.rs
Labels: bug, fuelup

#666 Extend finding components to plugins and executables distributed by forc
  component/src/lib.rs
Labels: bug, code quality, fuelup
