Repository FuelLabs/fuelup, pull requests merged in 2025-03, with the labels that each got.

#705 fix: typos in documentation files
  docs/src/basics.md
Labels: cla:signed

#709 Keep compiler explorer synced with the mainnet version of `forc`
  .github/workflows/update-compiler-explorer.yml
  Cargo.lock
  Cargo.toml
  ci/update-compiler-explorer/Cargo.toml
  ci/update-compiler-explorer/src/git.rs
  ci/update-compiler-explorer/src/main.rs
Labels: ci

#710 chore: bump version to v0.27.1
  Cargo.lock
  Cargo.toml
Labels: release
