Repository FuelLabs/fuelup, pull requests merged in 2025-05, with the labels that each got.

#731 Fix: Resolve git auth and upstream errors in update-compiler-explorer script
  .gitignore
  ci/update-compiler-explorer/src/git.rs
  ci/update-compiler-explorer/src/main.rs
Labels: ci

#735 chore: bump to v0.27.3
  Cargo.lock
  Cargo.toml
Labels: release

#736 tests: actually point to yesterday for nightly overrides
  tests/testcfg/mod.rs
Labels: testing
